// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/cristianadrielbraun/qrcreator.link/web/layouts"
)

func privacyContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"mx-auto max-w-3xl py-8\"><h1 class=\"text-2xl md:text-3xl font-semibold tracking-tight\">Privacy</h1><p class=\"mt-4 text-slate-700 dark:text-slate-300\">Last updated: 13-09-25</p><p class=\"mt-6\">I built qrcreator.link to be fast, simple, open‑source, and privacy‑friendly. You can always review the full source code on GitHub.</p><h2 class=\"mt-8 text-lg font-semibold\">Data collection</h2><p class=\"mt-2\">I do not use tracking cookies and I do not require accounts. The URL you enter is processed only to generate a QR code and is not stored by me.</p><h2 class=\"mt-6 text-lg font-semibold\">Logs</h2><p class=\"mt-2\">I only keep real‑time runtime logs in memory for operational purposes. I do not persist access or application logs to disk or external storage.</p><h2 class=\"mt-6 text-lg font-semibold\">Generated QR codes</h2><p class=\"mt-2\">QR codes are generated on demand and streamed back to your browser. I do not persist generated images.</p><h2 class=\"mt-6 text-lg font-semibold\">Third‑party services</h2><p class=\"mt-2\">The site is served through my infrastructure with a reverse proxy for TLS/edge routing. No analytics or advertising trackers are included.</p><h2 class=\"mt-6 text-lg font-semibold\">Contact</h2><p class=\"mt-2\">Questions or feedback? Reach me on <a class=\"underline\" href=\"https://github.com/cristianadrielbraun\" target=\"_blank\" rel=\"noopener\">GitHub</a>, <a class=\"underline\" href=\"https://twitter.com/MonitoBraun\" target=\"_blank\" rel=\"noopener\">Twitter</a>, or <a class=\"underline\" href=\"https://bsky.app/profile/monitobraun.bsky.social\" target=\"_blank\" rel=\"noopener\">Bluesky</a>.</p></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func PrivacyPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = layouts.Layout("Privacy Policy – qrcreator.link", privacyContent()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
